import Link from "next/link";
import type { Metadata } from "next";
import styles from "./risk.module.css";

export const metadata: Metadata = { title: "Risk & security", description: "Understand ICFT LTV limits, liquidations, oracle dependencies, LP risk and testnet limitations." };

const safeguards = [
  ["Collateral limits", "Borrowing and withdrawals are checked against collateral value, existing debt and configured LTV limits."],
  ["Fresh price checks", "The PriceOracle uses configured data feeds and rejects data that exceeds its maximum freshness window."],
  ["Liquidation path", "Unsafe positions can be repaid and liquidated under on-chain rules to protect the lending pool."],
  ["Insurance reserve", "A portion of interest is reserved as a first-loss buffer before bad debt reaches LP capital."],
] as const;

export default function RiskPage() {
  return <main className={styles.page}>
    <nav className={`${styles.nav} shell`}><Link href="/" className="brand"><span>ICFT</span><i>+</i></Link><div className={styles.links}><Link href="/how-it-works">How it works</Link><Link href="/tokenomics">Tokenomics</Link><Link href="/faq">FAQ</Link></div><Link className={styles.return} href="/dapp">Open dApp ↗</Link></nav>
    <section className={`${styles.hero} shell`}><div><span className="kicker">ICFT / RISK & SECURITY</span><h1>Know the edge<br /><em>before you use it.</em></h1><p>Collateralized lending reduces some risks. It does not remove market volatility, smart-contract risk, oracle risk, liquidity risk or the possibility of loss. This page explains the current Sepolia baseline in plain language.</p></div><div className={styles.gauge}><span>TESTNET RISK LIMITS</span><strong>80<small>%</small></strong><b>MAX LTV</b><div><i>90% liquidation threshold</i><i>5% liquidation bonus</i></div></div></section>
    <section className={`${styles.warning} shell`}><b>TESTNET ONLY</b><p>The deployed system is an early-stage Sepolia baseline. Do not use mainnet assets, do not treat values as production-ready, and do not assume current parameters are permanent.</p><Link href="/faq">Read operational FAQ ↗</Link></section>
    <section className={`${styles.ltv} shell`}><div><span className="kicker">POSITION HEALTH</span><h2>LTV is the number<br />to watch.</h2><p>Loan-to-value compares your USD debt against your USD collateral value. As collateral prices fall or interest accrues, LTV rises. The dApp displays the current position, but users remain responsible for monitoring it.</p></div><div className={styles.scale}><div><span>0%</span><span>80%</span><span>90%</span><span>100%</span></div><i><b className={styles.safe}>Healthy borrowing range</b><b className={styles.caution}>Manage closely</b><b className={styles.danger}>Liquidation eligible</b></i><p><strong>80% max LTV</strong> New borrowing and collateral withdrawal are blocked above this limit.</p><p><strong>90% threshold</strong> The position can become eligible for liquidation under protocol rules.</p></div></section>
    <section className={`${styles.safeguards} shell`}><div className={styles.sectionHead}><span className="kicker">WHAT THE PROTOCOL ENFORCES</span><h2>Designed to<br />contain damage.</h2></div><div className={styles.safeguardGrid}>{safeguards.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={`${styles.risks} shell`}><div><span className="kicker">WHAT IT CANNOT PROMISE</span><h2>Risks remain<br />with the user.</h2></div><div>{[["Market volatility", "Collateral value can move quickly, including between your last check and a transaction confirmation."],["Liquidity risk", "LP shares may not be redeemable immediately if capital is currently borrowed or pool liquidity is insufficient."],["Oracle and dependency risk", "Feeds, RPC services, wallets and external infrastructure can fail, become stale or behave unexpectedly."],["Smart-contract and upgrade risk", "The system is upgradeable and still early-stage. An audit or test result does not eliminate implementation risk."],["Liquidation execution risk", "A liquidator may execute when the threshold is crossed. You should not rely on notifications or bots as your only protection."]].map(([title, body]) => <article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className={`${styles.checklist} shell`}><div><span className="kicker">BEFORE EVERY ACTION</span><h2>A short safety check.</h2></div><ol><li>Confirm the wallet account and Ethereum Sepolia network.</li><li>Check collateral, debt, LTV and the transaction amount in the dApp.</li><li>Leave a meaningful LTV buffer rather than borrowing to the displayed maximum.</li><li>Read wallet approvals and transaction targets before signing.</li><li>Use a separate test-only wallet and never disclose a seed phrase.</li></ol></section>
    <section className={`${styles.end} shell`}><div><span>TRANSPARENCY OVER ASSURANCE</span><h2>Explore the<br /><em>protocol carefully.</em></h2></div><Link className="button primary" href="/dapp">Open dApp <b>↗</b></Link></section>
  </main>;
}
